"""
Issue 24: End-to-end integration test for the pipeline.

WHAT THIS TESTS
---------------
The downstream half of the pipeline:

    npy files --> Dataset_npy_collated --> DataLoader --> BST_0 forward pass

Specifically it verifies that:
  1. Real preprocessed npy files can be loaded by Dataset_npy_collated
  2. The DataLoader correctly batches them
  3. The human_pose tensor can be flattened into the feature dim the model expects
     (same operation as bst_train.py:101)
  4. BST_0 runs a forward pass without error
  5. The output shape is (batch_size, n_classes) — i.e. one prediction per sample

WHAT THIS DOES NOT TEST
-----------------------
The upstream half of the pipeline:
  - Raw ShuttleSet CSV annotation parsing
  - Class collapse (apply_class_merge)
  - Split assignment (train/val/test)
  - Preprocessing: pose extraction (MMPose) and shuttle extraction (TrackNetV3)
  - Correctness of class labels in the real data
  - Model training or accuracy

These steps require real videos, MMPose, and TrackNetV3 — HPC only. They are
owned by Jared (clip generation) and Ariel (preprocessing/shuttle extraction).
This test implicitly validates their output is correctly formatted if it passes.

HOW TO RUN ON HPC
-----------------
Once the npy dataset has been generated by prepare_train_on_shuttleset.py, set
BST_DATA_DIR to the ablation-tagged npy_{ablation_id} directory (optionally
prefixed with 3d_ or seq{N}_ for non-default configs) and run pytest:

    BST_DATA_DIR=/path/to/npy_une_merge_v1_split_v2_dropunk \
        pytest tests/test_integration.py -v

The dataset directory should contain train/, val/, and test/ subdirectories,
each with J_only.npy (or JnB_bone.npy etc.), pos.npy, shuttle.npy,
videos_len.npy, and labels.npy.
"""

import os
import pytest
import torch
from pathlib import Path
from torch.utils.data import DataLoader

from src.bst_refactor.stroke_classification.preparing_data.shuttleset_dataset import (
    Dataset_npy_collated,
)
from src.bst_refactor.stroke_classification.model.bst import BST_0
from src.bst_refactor.pipeline.config import TAXONOMIES, DEFAULT_TAXONOMY

BST_DATA_DIR = os.environ.get("BST_DATA_DIR")

@pytest.mark.skipif(
    not BST_DATA_DIR or not Path(BST_DATA_DIR).exists(),
    reason=(
        "BST_DATA_DIR not set or does not exist. "
        "Set BST_DATA_DIR to an npy_[3d_][seq{N}_]{ablation_id} directory "
        "on HPC and re-run."
    ),
)
def test_pipeline_dataloader_to_model_forward_pass():
    # -------------------------------------------------------------------------
    # UPSTREAM STEPS (not tested here — require HPC, real videos, MMPose, TrackNetV3)
    # -------------------------------------------------------------------------
    # Step 1: Parse raw ShuttleSet CSV annotations
    #   Owner: Jared
    #   Script: pipeline/clip_generator.py -> generate_all_clips()
    #
    # Step 2: Class collapse and split assignment
    #   Owner: Jared
    #   Script: pipeline/clip_generator.py -> apply_class_merge()
    #
    # Step 3: Pose extraction (MMPose) and shuttle extraction (TrackNetV3) -> npy files
    #   Owner: Ariel
    #   Script: stroke_classification/preparing_data/prepare_train_on_shuttleset.py
    #
    # Once the above are complete, point BST_DATA_DIR at the
    # npy_{ablation_id} directory (optionally prefixed with 3d_ or seq{N}_
    # for non-default configs) and the steps below will validate the full
    # downstream pipeline.
    # -------------------------------------------------------------------------

    n_classes = TAXONOMIES[DEFAULT_TAXONOMY].n_classes

    # Step 4: Load npy dataset.
    # Active configs only collate one pose_style at a time (J_only / JnB_bone /
    # JnB_interp / Jn2B). Pick whichever is present in the test split rather
    # than hard-coding the default; lets the test pass against any collated
    # ablation without manual setup.
    test_dir = Path(BST_DATA_DIR) / "test"
    candidate_styles = ("JnB_bone", "Jn2B", "JnB_interp", "J_only")
    pose_style = next(
        (s for s in candidate_styles if (test_dir / f"{s}.npy").exists()),
        None,
    )
    assert pose_style is not None, (
        f"No pose_style file (one of {candidate_styles}) found in {test_dir}. "
        f"Re-run prepare_train_on_shuttleset with --pose-styles before this test."
    )
    dataset = Dataset_npy_collated(Path(BST_DATA_DIR), "test", pose_style=pose_style)
    assert len(dataset) > 0, (
        "Dataset is empty — check BST_DATA_DIR points to the correct "
        "npy_{ablation_id} directory and that the test/ split exists."
    )

    # Step 5: Batch via DataLoader
    loader = DataLoader(dataset, batch_size=4, shuffle=False, num_workers=0)
    (human_pose, pos, shuttle), video_len, labels = next(iter(loader))
    assert human_pose.ndim == 5, (
        f"Expected human_pose to have 5 dims (batch, frames, players, joints, xy), "
        f"got shape {human_pose.shape} — preprocessing output may be malformed."
    )

    # Step 6: Flatten joints/bones into feature dim (mirrors bst_train.py:101)
    human_pose = human_pose.view(*human_pose.shape[:-2], -1)
    in_dim = human_pose.shape[-1]
    seq_len = human_pose.shape[1]
    assert in_dim > 0, (
        f"Flattened in_dim is {in_dim} — something is wrong with the pose tensor shape."
    )

    # Step 7: Instantiate BST_0 and run forward pass
    model = BST_0(in_dim=in_dim, seq_len=seq_len, n_class=n_classes, d_model=100)
    model.eval()

    with torch.no_grad():
        output = model(human_pose, shuttle, pos, video_len)

    assert output.shape == (4, n_classes), (
        f"Expected output shape (4, {n_classes}), got {output.shape} — "
        f"check n_classes matches the taxonomy used during preprocessing."
    )
